### How the calculation in dropouts work?

Bernoulli's Random Variable Calculation

In [6]:
# This conatins the bernaulli distribution 
import tensorflow_probability as tfp 
import tensorflow as tf

In [10]:
keeping_prob = 0.7
r = tfp.distributions.Bernoulli(probs = keeping_prob, dtype = tf.float32).sample(sample_shape = (10,1))

In [11]:
# We are looking for a (10,1) column matrix network 
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.]], dtype=float32)>

In [12]:
# Lets say we have the values coming in from the prev layers also in a (10,1) fashion
y_prev = tf.random.normal((10,1))
y_prev

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 1.2639349 ],
       [ 1.4258683 ],
       [-0.52409965],
       [-0.21170476],
       [-1.5714499 ],
       [ 0.6273802 ],
       [ 0.60202545],
       [ 1.0974052 ],
       [ 1.5483238 ],
       [-1.2707598 ]], dtype=float32)>

In [13]:
# This is how we calculate the new Y with switch off and switch on types 
y_new = tf.math.multiply(y_prev,r)
y_new

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 1.2639349 ],
       [ 0.        ],
       [-0.        ],
       [-0.        ],
       [-1.5714499 ],
       [ 0.6273802 ],
       [ 0.60202545],
       [ 1.0974052 ],
       [ 1.5483238 ],
       [-0.        ]], dtype=float32)>

In [ ]:
# Once the training happens we multiply the weights with p 

### Dropout

Implementation 

In [14]:
from tensorflow import keras

In [15]:
# rate is a keeping probablity. Keep it between 0.5 and 1 
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])
# n_epochs = 2
# history = model.fit(X_train_scaled, y_train, epochs=n_epochs,
#                     validation_data=(X_valid_scaled, y_valid))

In [16]:
# Some complexity is increasing 
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dropout (Dropout)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                1